version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../infrastructure/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: payments_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
